//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryId { get; set; }
        public Nullable<bool> Comedy { get; set; }
        public Nullable<bool> Drama { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<bool> Animation { get; set; }
        public Nullable<bool> SciFi { get; set; }
        public int Movie { get; set; }
    
        public virtual Movie Movie1 { get; set; }
    }
}
