//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultiplexTrackDbContext : DbContext
    {
        public MultiplexTrackDbContext()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<MovieShowtime> MovieShowtime { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Theatre> Theatre { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TimeSlot> TimeSlot { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
