//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlot
    {
        public int TimeSlotId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int MovieShowTimeId { get; set; }
        public int UserId { get; set; }
    
        public virtual MovieShowtime MovieShowtime { get; set; }
        public virtual User User { get; set; }
    }
}
